packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  expo-modules-jsi@57.1.0: patches/expo-modules-jsi@57.1.0.patch

overrides:
  "cassandra-driver>adm-zip": 0.6.1

minimumReleaseAgeExclude:
  - expo-image-picker@57.0.18
